[garden]
  title   = 'garden-bed'
  root    = 'i.root'

[format]
  attrs   = 'caml'

[doc]
  [doc.kind]
    [doc.kind.default]
      path   = '/'
      color  = '#3e5c50'
    [doc.kind.zombie]
      icon  = '🧟'
      color = '#959DA5'
    [doc.kind.template]
      path   = '/template/'
      prefix = 't.' # '+'
      icon   = '🧩'
      color  = '#F8F0E3'
