# attr types

antonym = { sync = "antonym" }
ctime   = { compute = "created" }
id      = { compute = "id" }
mtime   = { compute = "modified" }
synonym = { sync = "synonym" }
title   = {}
tldr    = {}
vtime   = { compute = "viewed" }
