[doc]
path   = "/"
color  = "#31AF31"
attrs  = ['id', 'ctime', 'mtime', 'vtime', 'title', 'tldr']

[index]
path   = "/index/"
prefix = "i."
emoji  = "🗄"
color  = "#F0C61F"
attrs  = ['id', 'ctime', 'mtime', 'vtime', 'title']
# emoji  = "🪵" ; bonsai.trunk

[entry]
path   = "/entries/"
emoji  = "🏷"
color  = "#31AF31"
attrs  = ['id', 'ctime', 'mtime', 'vtime', 'title', 'tldr', 'synonym', 'antonym']
# emoji  = "🍃"; bonsai.leaf

[daily-note]
path   = "/daily-note/"
emoji  = "📓"
attrs  = ['id', 'ctime', 'mtime', 'vtime']
# emoji  = "🍃"; bonsai.leaf

[book]
path   = "/book/"
prefix = "bk."
emoji  = "📚"
