[doc]
path   = "/"
color  = "#31AF31"
attrs  = ['id', 'ctime', 'mtime', 'vtime', 'title', 'tldr']

[index]
path   = "/index/"
prefix = "i."
icon   = "🗄"
color  = "#F0C61F"
attrs  = ['id', 'ctime', 'mtime', 'vtime', 'title']
# icon   = "🪵" ; bonsai.trunk

[entry]
path   = "/entries/"
icon   = "🏷"
color  = "#31AF31"
attrs  = ['id', 'ctime', 'mtime', 'vtime', 'title', 'tldr', 'synonym', 'antonym']
# icon   = "🍃"; bonsai.leaf

[daily-note]
path   = "/daily-note/"
icon   = "📓"
attrs  = ['id', 'ctime', 'mtime', 'vtime']
# icon   = "🍃"; bonsai.leaf

[book]
path   = "/book/"
prefix = "bk."
icon   = "📚"
