[garden]
  title   = 'garden-bed'
  root    = 'i.bonsai'

[format]
  attrs       = 'caml'
  mkdn_bullet = 'dash'
  indent_kind = 'space'
  indent_size = 2

[doc]
  [doc.kind]
    [doc.kind.default]
      path   = '/'
      color  = '#3e5c50'
    [doc.kind.zombie]
      emoji = '🧟'
      color = '#959DA5'
    [doc.kind.template]
      path   = '/template/'
      prefix = 't.' # '+'
      emoji  = '🧩'
      color  = '#F8F0E3'
