# doctypes

[doc]
path   = "/"
color  = "#31AF31"
attrs  = ['title', 'id', 'ctime', 'mtime', 'vtime']

[index]
path   = "/tree/index/"
prefix = "i."
color  = "#F0C61F"
icon   = "🗄"
# icon   = "🪵" ; bonsai.trunk

[entry]
path   = "/tree/entries/"
color  = "#31AF31"
icon   = "🏷"
# icon   = "🍃"; bonsai.leaf

[daily-note]
path   = "/daily-note/"
color  = ""
icon   = "📓"
attrs  = ['id', 'ctime', 'mtime', 'vtime']

[book]
path   = "/books/"
prefix = "bk."
color  = "#fb3f2b"
icon   = "📚"
attrs  = ['title', 'subtitle', 'author', 'pdate']
