# doctypes

[doc]
path   = "/"
color  = "#31AF31"
attrs  = ['title', 'id', 'ctime', 'mtime', 'vtime']

[index]
path   = "/index/"
prefix = "i."
color  = "#F0C61F"
emoji  = "🗄"
# emoji  = "🪵" ; bonsai.trunk

[entry]
path   = "/entries/"
color  = "#31AF31"
emoji  = "🏷"
# emoji  = "🍃"; bonsai.leaf

[daily-note]
path   = "/daily-note/"
color  = ""
emoji  = "📓"
attrs  = ['id', 'ctime', 'mtime', 'vtime']

[book]
path   = "/books/"
prefix = "bk."
color  = "#fb3f2b"
emoji  = "📚"
attrs  = ['title', 'subtitle', 'author', 'pdate']
