[default]
path  = "/"
color = "#3e5c50"
attrs = ['id', 'ctime', 'mtime']

[index]
path   = "/index/"
prefix = "i."
icon   = "🗄"
color  = "#F0C61F"
attrs  = []

[entry]
path  = "/entries/"
icon  = "🏷"
color = "#3e5c50"
attrs = ['hypernym', 'hyponym', 'synonym', 'antonym', 'title', 'tldr']
